name: Moderrn Jekyll Site
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
logo: false
paginate: 8
gems: [jekyll-paginate]
permalink:    /:year/:month/:day/:title/
baseurl: ""


# Details for the RSS feed generator
